### ISSUE TITLE
Error in matrix_stack constructor

### ISSUE THREAD

**Issue by YohannPerron** [drohmer/CGP-2021#1]
**Context:**
I am currently trying to compute $B = v*u^T$ where $B$ is a mat3 and "v,u" are vec3
The best solution that I found is to convert u and v to matrix_stack<3,1> and <1,3> respectively.

> matrix_stack<float, 3, 1> m_v = v;
> matrix_stack<float, 1, 3> m_u = u;

**Error**
However, the second conversion gives me an error:

> Error found at this point of the code:
>   - Function: check_index_bounds
>   - Error message:                                                                        P2\INF585\code_inf585\library\cgp\containers\buffer_stack\implementation/buffer_stack.hpp
>  - Try access buffer_stack[3]
>  - With container size =3
>  - Buffer type: vec3
>         > Index reached the maximal size of the buffer
>         > The maximal possible index should be 2
>           Help:
>              C++ has index starting at 0.
>              Typical loops should go from index=0 to index<buffer.size().
>           The function and variable that generated this error can be found in analysis the Call Stack.

**Origin**

From what I understand, it relies on the constructor : matrix_stack(buffer_stack<T, N1* N2> const& elements).
Inside the constructor, you used offset_grid_stack\<N2\>(k1, k2) [(line 232)](https://github.com/drohmer/CGP/blob/dd6dc68af95d7b9a0a0b8d88a5760091e6dc3d38/library/cgp/math/matrix/matrix_stack/matrix_stack.hpp#L232) to access the elements of the flat buffer_stack.
It is my understanding that you should call  offset_grid_stack\<N1\>(k1, k2) instead.

**Comment by drohmer** [comment]
Thanks, yes this line assume that the vec3 is considered as a column vector.

This function should work better, I'll patch it up:

    template <typename T, int N1, int N2>
    matrix_stack<T, N1, N2>::matrix_stack(buffer_stack<T, N1* N2> const& elements)
        : data()
    {
        int counter = 0;
        for (int k1 = 0; k1 < N1; ++k1)
            for (int k2 = 0; k2 < N2; ++k2) {
                at_unsafe(k1, k2) = elements[counter];
                counter++;
            }
    }
