### ISSUE TITLE
Error in fill for matrix_stack

### ISSUE THREAD

**Issue by YohannPerron** [drohmer/CGP-2021#2]
Error:
I got the following error will calling the fill function on a mat3:
error C4716: 'cgp::matrix_stack<float,3,3>::fill': must return a value

Solution:
`return *this ;` should be added at the end of the function (as it is the case with vec3).
https://github.com/drohmer/CGP/blob/94f42831ffd46340526ea0d70a18bf5184f19e3b/library/cgp/math/matrix/matrix_stack/matrix_stack.hpp#L287

**Comment by drohmer** [comment]
Absolutely, thanks.
